In [35]:
# By using Desicision tree
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

In [36]:
data = pd.read_csv("Position_Salaries.csv")
data

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [37]:
real_x = data.iloc[:,1:2].values #real_x = data.iloc[:,1] --> now it is vector..but we need array that why we select [1:2]--> means 2-1 =1
real_y = data.iloc[:,2].values
real_x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=int64)

In [38]:
reg = RandomForestRegressor(n_estimators=400,random_state = 0) #n_estimators:- we perform decision tree many times--> this represents the no. of pemorme ---> by default itis 10 

In [39]:
reg.fit(real_x,real_y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=400,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [40]:
y_pred = reg.predict([[6.5]])
y_pred

array([160500.])

In [41]:
x_grid = np.arange(min(real_x),max(real_x),0.01)  #(x,x,steps-->ressolution)
x_grid = x_grid.reshape(len(x_grid),1)
x_grid

array([[1.  ],
       [1.01],
       [1.02],
       [1.03],
       [1.04],
       [1.05],
       [1.06],
       [1.07],
       [1.08],
       [1.09],
       [1.1 ],
       [1.11],
       [1.12],
       [1.13],
       [1.14],
       [1.15],
       [1.16],
       [1.17],
       [1.18],
       [1.19],
       [1.2 ],
       [1.21],
       [1.22],
       [1.23],
       [1.24],
       [1.25],
       [1.26],
       [1.27],
       [1.28],
       [1.29],
       [1.3 ],
       [1.31],
       [1.32],
       [1.33],
       [1.34],
       [1.35],
       [1.36],
       [1.37],
       [1.38],
       [1.39],
       [1.4 ],
       [1.41],
       [1.42],
       [1.43],
       [1.44],
       [1.45],
       [1.46],
       [1.47],
       [1.48],
       [1.49],
       [1.5 ],
       [1.51],
       [1.52],
       [1.53],
       [1.54],
       [1.55],
       [1.56],
       [1.57],
       [1.58],
       [1.59],
       [1.6 ],
       [1.61],
       [1.62],
       [1.63],
       [1.64],
       [1.65],
       [1.

In [ ]:
plt.scatter(real_x,real_y,color = "green")
plt.plot(x_grid, reg.predict(x_grid), color = "blue")
plt.title("Random Forest Regressor")
plt.xlabel("Pos Level")
plt.ylabel("Salary")
plt.show()

In [ ]:
# Good Result then Decision Tree Regression and Polynomial Regression